# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.srcs/sources_1/ip/ibert_ultrascale_gth_1/ibert_ultrascale_gth_1.xci
# IP: The module: 'ibert_ultrascale_gth_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/ibert_ultrascale_gth_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/ibert_ultrascale_gth_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.srcs/sources_1/ip/ibert_ultrascale_gth_1/ibert_ultrascale_gth_1.xci
# IP: The module: 'ibert_ultrascale_gth_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/ibert_ultrascale_gth_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/ibert_ultrascale_gth_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/sw_mcs_all.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/bouthsarath/ibert_ultrascale_gth_1_ex/ibert_ultrascale_gth_1_ex.gen/sources_1/ip/ibert_ultrascale_gth_1/synth/attributes.xdc
# XDC: The top module name and the constraint reference have the same name: 'ibert_ultrascale_gth_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
